/**

   © Copyright 2017 Edgar Aguiniga ©
   This file is part of LoginPwds.

   LoginPwds is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   LoginPwds is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with LoginPwds.  If not, see <http://www.gnu.org/licenses/>.

 **/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.03 at 05:58:15 AM MST 
//


package net.ea.loginpwds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cipher_info complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cipher_info">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="secure_hash_algorithm" type="{}secure_hash_algorithm"/>
 *         &lt;element name="encryption_algorithm_info" type="{}encryption_algorithm_info"/>
 *         &lt;element name="initialization_vector" type="{}initialization_vector"/>
 *         &lt;element name="salt" type="{}salt"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cipher_info", propOrder = {
    "secureHashAlgorithm",
    "encryptionAlgorithmInfo",
    "initializationVector",
    "salt"
})
public class CipherInfo {

    @XmlElement(name = "secure_hash_algorithm", required = true)
    protected String secureHashAlgorithm;
    @XmlElement(name = "encryption_algorithm_info", required = true)
    protected String encryptionAlgorithmInfo;
    @XmlElement(name = "initialization_vector", required = true)
    protected String initializationVector;
    @XmlElement(required = true)
    protected String salt;

    /**
     * Gets the value of the secureHashAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecureHashAlgorithm() {
        return secureHashAlgorithm;
    }

    /**
     * Sets the value of the secureHashAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecureHashAlgorithm(String value) {
        this.secureHashAlgorithm = value;
    }

    /**
     * Gets the value of the encryptionAlgorithmInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncryptionAlgorithmInfo() {
        return encryptionAlgorithmInfo;
    }

    /**
     * Sets the value of the encryptionAlgorithmInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptionAlgorithmInfo(String value) {
        this.encryptionAlgorithmInfo = value;
    }

    /**
     * Gets the value of the initializationVector property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitializationVector() {
        return initializationVector;
    }

    /**
     * Sets the value of the initializationVector property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitializationVector(String value) {
        this.initializationVector = value;
    }

    /**
     * Gets the value of the salt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalt() {
        return salt;
    }

    /**
     * Sets the value of the salt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalt(String value) {
        this.salt = value;
    }

}
